### ISSUE TITLE
Response status code does not indicate success: 401 (Unauthorized)

### ISSUE THREAD

**Issue by jinqiufeng** [jerry08/SoundCloudDownloader#8]
Hey. The app hasn't been working for several days and this error occurs every time. Is there a solution?

I didn't find any logs, lemme know how to do it if necessary.

**Comment by jerry08** [comment]
The ClientId needed to be updated ([see issue](https://github.com/jerry08/SoundCloudExplode/issues/2)). It's fixed in the latest version of [**SoundCloudExplode**](https://www.nuget.org/packages/SoundCloudExplode). I haven't updated the package in this repo yet but I will do it soon. Also, I started porting the entire project to Avalonia.

**Comment by jinqiufeng** [comment]
Gonna wait for the update. I haven't found any better alternatives to this.

**Comment by jerry08** [comment]
An update is now available which fixes the issue. Also, you can now download the app for Windows, MacOS or Linux.
